name: My Complete DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:  # Lowercase "push" (convention)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Lowercase "checkout"
      
      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV  # No space before colon, no space in $GITHUB_ENV
      
      - name: Login to DockerHub  # Correct spelling
        run: |  # "run:" not "runs:"
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" \
            --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t bradtech360/complete-devops-project:${{ env.SHORT_SHA }} .
      
      - name: Push Docker imag
        run: |
          docker push bradtech360/complete-devops-project:${{ env.SHORT_SHA }}

      - name: Configure Git Authorship
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Update Helm Chart with new image tag
        run: |
          sed -i "s/tag: .*/tag: \"${{ env.SHORT_SHA }}\"/" complete-devops-project-time-printer/values.yaml
          git add complete-devops-project-time-printer/values.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push