name: My complete Devops CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  build_and_Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (This downloads our repository code to the runner)
        uses: actions/Checkout@v4
      - name: set SHORT_SHA (SHORT_SHA is the first 7 characters of the commit SHA)
        run : echo "SHORT_SHA=${GITHUB_SHA::7}" >> $ GITHUB_ENV
      - name: login to DokerHub
        runs: |
          echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login \
          -u "${{secrets.DOCKER_HUB_USERNAME}}" --password-stdin
      - name: Build image
        run: |
          docker build -t bradtech360/complete-devops-project:${{env.SHORT_SHA}} .
      - name: Push image to DockerHub
        run: |
          docker push bradtech360/complete-devops-project:${{env.SHORT_SHA}}